### ISSUE TITLE
WindowsFirewallLogSize value too high

### ISSUE THREAD

**Issue by SwaffelSmurf** [eneerge/CIS-Windows-Server-2022#6]
Default value in the script is 4GB. Maximum value allowed is 32767 KB. Source: [Windows Defender Firewall: Allow logging](https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.WindowsFirewall::WF_Logging_Name_2)

When 4GB is set, the firewall mmc crashes when opening the 'Customize...' dialog under the section Logging.

**Comment by eneerge** [comment]
I didn't have this issue, but I also didn't have a large log. I've gone ahead and updated max size to 32MB.
