### ISSUE TITLE
Script is failing

### ISSUE THREAD

**Issue by tej0402** [eneerge/CIS-Windows-Server-2022#8]
Hi there!

Script is failing at 595 line....with the below message in 2022 server.
```
At C:\Users\Administrator\Desktop\Win22HardenScript.ps1:595 char:9
+         throw $message
+         ~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Configuring 'Se...ol.cfg' failed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Configuring 'SecurityPolicy' via C:\Users\Administrator\AppData\Roaming\secpol.cfg' fail
   ed.
```

**Comment by tej0402** [comment]
> Hi there!
> 
> Script is failing at 595 line....with the below message in 2022 server.
> 
> ```
> At C:\Users\Administrator\Desktop\Win22HardenScript.ps1:595 char:9
> +         throw $message
> +         ~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (Configuring 'Se...ol.cfg' failed.:String) [], RuntimeException
>     + FullyQualifiedErrorId : Configuring 'SecurityPolicy' via C:\Users\Administrator\AppData\Roaming\secpol.cfg' fail
>    ed.
> ```

This is because of more characters in Logon Message. I have kept only one sentence now script has been executed.

**Comment by eneerge** [comment]
Thanks for the fix. I will see if I can add max character validation.
