### ISSUE TITLE
RDP is not working

### ISSUE THREAD

**Issue by tej0402** [eneerge/CIS-Windows-Server-2022#9]
Hi,

I ran script and executed successfully. But unfortunately I have lost connection to RDP. 

I am doing hardening from Standalone server.

**Comment by eneerge** [comment]
Hello,

Do you use a local account or an active directory account to RDP?

**Comment by eneerge** [comment]
tej0402,

I just set up a fresh Windows Server 2019, performed all Windows updates, and then ran this script.

RDP still works.

If you are trying to remote in as "Administrator", you will need to change the user to the name of the user you set in the script. By default, that is just simple "User".

After running the script and then rebooting, I could still remote in through RDP using the username "User".

**Comment by tej0402** [comment]
Thank you for the update @eneerge.
